### ISSUE TITLE
数据集处理

### ISSUE THREAD

**Issue by AllGGI** [yunzinan/BCI-emotion-recognition#1]

**Comment by yunzinan** [comment]
Thank you for pointing out this issue, which I suppose should be a MISTAKE. I think the right way to do it is, as you've suggested, to segment the raw data in time dimension, rather than directly using `reshape`.

**Comment by yunzinan** [comment]
> 你好，在conformer中，在把47000数据划分为58个长度为800的片段，一般是把一段信号前800个数据点作为一个样本，再切800个再作为另一样本，为什么代码中是划分成800个长度为58的片段，再从每个片段中取出对应数据点组成一个新的长为800的样本，这样做确实能得出很高acc，但是这种做法有没有什么依据？

I've  fixed the bug and redo the experiments on `conformer-sub1`, `gru-sub1`, `LSTM-sub1`. Sadly, the results were pretty bad. For the conformer model, the test accuracy didn't reach the result proposed in the paper. Therefore, I think this work isn't a successful implementation. I would examine the codes and try to find out the problem later when I have time for it😥. 

Anyway, I will update the codes and results for your inference. Sorry for the stupid mistake I made.

By the way, In terms of the pretty good results yielded from the wrong impl. , I think it would be meaningless as both train data and test data were totally wrong. 🤣. Again, sorry for that.
